### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)

### ISSUE THREAD

**Issue by Sda2023** [tr0uble-mAker/POC-bomber#1]
Hi
How do I fix this?

**Comment by tr0uble-mAker** [comment]
I don't know what the specific situation is on your side, but I guess the probability is caused by incorrect Chinese decoding. If you can describe it more specifically (such as what command you executed caused this error) or email some relevant pictures to me, I will be able to better solve it. Please make sure is the library in  /requirement.txt  fully installed? Or is it run with Python3? Please check that you have correctly downloaded and installed pocbomber according to the instructions, because it seems good in Kali Linux and Windows on my side.

**Comment by tr0uble-mAker** [comment]
![image](https://user-images.githubusercontent.com/71172892/150809481-3cfb6002-d17a-43f5-9513-96b7915865c0.png)

I have just successfully reproduced the error you said. This may be due to the fact that the default code of Python 3 is Latin-1. The solution can be solved by entering the command  `export PYTHONIOENCODING=utf-8`  in the terminal, use this command to change the environment variable to UTF-8 or you can solve the problem by [reading this article](https://blog.csdn.net/m0_37885286/article/details/108671215). Thank you again for your support and suggestions, have a nice day! :   )

**Comment by Sda2023** [comment]
> ![image](https://user-images.githubusercontent.com/71172892/150809481-3cfb6002-d17a-43f5-9513-96b7915865c0.png)
> 
> I have just successfully reproduced the error you said. This may be due to the fact that the default code of Python 3 is Latin-1. The solution can be solved by entering the command `export PYTHONIOENCODING=utf-8` in the terminal, use this command to change the environment variable to UTF-8 or you can solve the problem by [reading this article](https://blog.csdn.net/m0_37885286/article/details/108671215). Thank you again for your support and suggestions, have a nice day! : )

problem solved tnx
